import os
import sys
import logging
import time
import threading
from flask import Flask

# Modular components - Path fix
# Humne yahan check lagaya hai taaki 'utils' na milne par error na aaye
try:
    from utils import config
    from core_logic.writer_engine import SmartWriter
    from integrations.wordpress_api import WordPressClient
except ImportError as e:
    print(f"Error: Module missing! {e}")
    # Agar utils nahi mil raha toh path adjust karein
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    from utils import config
    from core_logic.writer_engine import SmartWriter
    from integrations.wordpress_api import WordPressClient

# --- RENDER PORT BINDING FIX ---
app = Flask(__name__)

@app.route('/')
def health_check():
    return "Nexovent Bot is Live and Running", 200

def run_health_server():
    # Render hamesha PORT environment variable deta hai, default 10000
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port, debug=False, use_reloader=False)

# Logging Setup
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s]: %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("NexoventBot")

def run_bot():
    # Server ko settle hone ke liye thoda zyada time dena behtar hai
    logger.info("Waiting for server to stabilize...")
    time.sleep(20) 
    
    logger.info("Automation workflow initiated...")
    try:
        writer = SmartWriter(api_key=config.AI_API_KEY)
        wp = WordPressClient(
            wp_url=config.WP_URL,
            username=config.WP_USERNAME,
            password=config.WP_APP_PASSWORD
        )
        
        # Topic selection
        topic = "Future of Artificial Intelligence 2026"
        logger.info(f"Generating article for topic: {topic}")
        
        article = writer.generate_article(topic)
        
        # Safety check for article content
        if isinstance(article, dict):
            body = article.get('body', "")
            title = article.get('title', topic)
        else:
            body = article
            title = topic
        
        if body:
            logger.info("Content generated. Sending to WordPress...")
            post_id = wp.post_full_article(
                title=title, 
                content=body, 
                status="draft"
            )
            if post_id:
                logger.info(f"SUCCESS! Article posted on earnguide.in with ID: {post_id}")
            else:
                logger.error("Failed to post article. Check WordPress credentials.")
        else:
            logger.warning("No content was generated by the AI.")
            
    except Exception as e:
        logger.error(f"Bot execution error: {str(e)}")

if __name__ == "__main__":
    # 1. Start Flask Server in background thread
    # Isse Render ko 'Live' signal mil jayega
    server_thread = threading.Thread(target=run_health_server)
    server_thread.daemon = True
    server_thread.start()
    
    # 2. Run the main bot logic
    run_bot()
    
    # 3. Final safety: Loop to keep the main process alive
    while True:
        time.sleep(3600)
