import os
import io
import re
import uuid
import logging
import requests
import hashlib
import asyncio
from typing import List, Optional, Dict, Any
from PIL import Image, ImageDraw, ImageFont
from urllib.parse import quote
from concurrent.futures import ThreadPoolExecutor

# Professional Logging Configuration
logger = logging.getLogger("SmartEcosystem.MediaManager")
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

class SmartMediaEngine:
    """
    Advanced Media Engine for AI Content Ecosystem.
    Supports: Pollinations.ai (Free High-Tier), WebP Compression, SEO Optimization, & Watermarking.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.brand_name = self.config.get("brand_name", "Nexovent AI")
        self.output_path = self.config.get("output_path", "static/assets/images")
        self.base_url = "https://image.pollinations.ai/prompt/"
        
        # Ensure production-ready directory structure
        os.makedirs(self.output_path, exist_ok=True)

    def _generate_seo_filename(self, keyword: str) -> str:
        """Generates a clean, SEO-optimized filename with a unique hash."""
        clean_name = re.sub(r'[^a-z0-9]+', '-', keyword.lower()).strip('-')
        unique_id = hashlib.md5(keyword.encode()).hexdigest()[:8]
        return f"{clean_name}-{unique_id}.webp"

    def _apply_pro_watermark(self, img: Image.Image) -> Image.Image:
        """Applies a sophisticated, semi-transparent watermark to the image."""
        try:
            overlay = Image.new('RGBA', img.size, (255, 255, 255, 0))
            draw = ImageDraw.Draw(overlay)
            
            # Position: Bottom Right
            w, h = img.size
            text = f"Generated by {self.brand_name}"
            
            # Using default font (can be upgraded to .ttf in production)
            draw.text((w - 200, h - 40), text, fill=(255, 255, 255, 120))
            
            return Image.alpha_composite(img.convert('RGBA'), overlay).convert('RGB')
        except Exception as e:
            logger.error(f"Watermark failed: {e}")
            return img

    def generate_image_sync(self, keyword: str, aspect_ratio: str = "16:9") -> Dict[str, Any]:
        """
        Synchronous wrapper for image generation. 
        Highly optimized for SEO and high-retention visuals.
        """
        logger.info(f"Initiating image generation for: {keyword}")
        
        # Advanced prompt engineering for Pollinations
        enhanced_prompt = (
            f"{keyword}, cinematic lighting, photorealistic, 8k resolution, "
            f"highly detailed, professional composition, award winning photography, "
            f"no text, no watermark, commercial grade"
        )
        
        encoded_prompt = quote(enhanced_prompt)
        width, height = (1280, 720) if aspect_ratio == "16:9" else (1024, 1024)
        seed = uuid.uuid4().int >> 64 # Unique seed for every request
        
        request_url = f"{self.base_url}{encoded_prompt}?width={width}&height={height}&seed={seed}&nologo=true&model=flux"

        try:
            response = requests.get(request_url, timeout=45)
            response.raise_for_status()
            
            # Process image in-memory
            img = Image.open(io.BytesIO(response.content))
            
            # Post-processing: Watermark & Branding
            img = self._apply_pro_watermark(img)
            
            # SEO Filename & Save
            filename = self._generate_seo_filename(keyword)
            final_path = os.path.join(self.output_path, filename)
            
            # Save as WebP (Industry standard for speed)
            img.save(final_path, "WEBP", quality=85, optimize=True)
            
            logger.info(f"Image successfully localized: {final_path}")
            
            return {
                "status": "success",
                "path": final_path,
                "url": f"/{final_path}",
                "alt_text": f"Professional visual representation of {keyword}",
                "metadata": {"width": width, "height": height, "format": "webp"}
            }

        except Exception as e:
            logger.error(f"Media Engine Error: {str(e)}")
            return {"status": "error", "message": str(e)}

    async def generate_image_async(self, keyword: str):
        """Asynchronous execution for high-concurrency environments."""
        loop = asyncio.get_event_loop()
        with ThreadPoolExecutor() as pool:
            return await loop.run_in_executor(pool, self.generate_image_sync, keyword)

# Module Export
if __name__ == "__main__":
    # Internal Testing
    engine = SmartMediaEngine({"brand_name": "Nexovent Pro"})
    result = engine.generate_image_sync("Future of Neural Networks in Business")
    print(result)
