"""
meta_tagger.py

Advanced metadata management for image SEO in content ecosystems.

Features:
 - EXIF Metadata Injection/Extraction/Update (Pillow/PieXif)
 - XMP Metadata Support (sidecar embedding)
 - Alt-text generation from article context
 - Automatic SEO-friendly file renaming
 - Batch directory processing
 - All metadata export as metadata.json
 - OOP: MetaManager class

Requires: pillow, piexif, lxml (for XMP), json, os, re, hashlib
"""

import os
import re
import json
import io
import hashlib
from typing import Dict, Optional, List
from PIL import Image, ExifTags
import piexif

# For XMP embedding
from lxml import etree

# --- Utility Functions ---

def slugify(text: str) -> str:
    """Convert a string into a slug suitable for filenames."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    text = text.strip('-')
    return text

def create_xmp_packet(metadata: Dict[str, str]) -> bytes:
    """
    Create a minimal XMP packet as bytes.
    """
    rdf = etree.Element("rdf:RDF", nsmap={
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "dc": "http://purl.org/dc/elements/1.1/",
        "xmp": "http://ns.adobe.com/xap/1.0/"
    })
    desc = etree.SubElement(rdf, "rdf:Description")

    for k, v in metadata.items():
        tag = etree.QName("http://purl.org/dc/elements/1.1/", k)
        desc.set(tag, v)

    xml_bytes = etree.tostring(rdf, pretty_print=True, xml_declaration=False, encoding='utf-8')
    xmp_packet = b'<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
    xmp_packet += b'<x:xmpmeta xmlns:x="adobe:ns:meta/">\n'
    xmp_packet += xml_bytes
    xmp_packet += b'\n</x:xmpmeta>\n<?xpacket end="w"?>'
    return xmp_packet

# --- Main Class ---

class MetaManager:
    """
    MetaManager: Injects, updates, and extracts image metadata for SEO.
    """

    def __init__(self, image_dir: str, author: str = "Nexovent AI"):
        self.image_dir = image_dir
        self.author = author
        self.metadata_records = []

    # ------- ALT Text Generator --------

    def generate_alt(self, context: str, base_name: str) -> str:
        """
        Generate SEO-optimized ALT text using context and basename.
        """
        # Rudimentary, for prod integrate with NLP for semantic enhancement.
        base = base_name.replace("-", " ")
        best = f"{context[:50]}, {base}".strip(" ,")
        return f"{best} - Generated by Nexovent AI"

    # ------- SEO Filename Generator ----

    def seo_filename(self, context: str, suffix: str = "jpg") -> str:
        slug = slugify(context)[:55]
        return f"{slug}.{suffix}"

    # ------- EXIF Metadata Injection ----

    def inject_exif(self, img_path: str, metadata: Dict[str, str]) -> None:
        """
        Injects metadata into EXIF tags of an image file.
        """
        try:
            img = Image.open(img_path)
            exif_dict = piexif.load(img.info.get('exif', b'') or b'')
            user_comment = metadata.get('Description', "")
            exif_dict['0th'][piexif.ImageIFD.Artist] = metadata.get("Author", "").encode('utf-8')
            exif_dict['0th'][piexif.ImageIFD.Copyright] = metadata.get("Copyright", "").encode('utf-8')
            if user_comment:
                exif_dict['Exif'][piexif.ExifIFD.UserComment] = piexif.helper.UserComment.dump(user_comment, encoding='unicode')
            exif_bytes = piexif.dump(exif_dict)
            img.save(img_path, exif=exif_bytes)
        except Exception as e:
            print(f"[EXIF Injection] {img_path} error: {e}")

    def extract_exif(self, img_path: str) -> Dict:
        """
        Extract readable EXIF metadata from image.
        """
        exif_data = {}
        try:
            img = Image.open(img_path)
            exif_dict = piexif.load(img.info.get('exif', b'') or b'')
            for ifd in exif_dict:
                for tag, value in exif_dict[ifd].items():
                    tag_name = piexif.TAGS[ifd][tag]["name"]
                    exif_data[tag_name] = value.decode('utf-8', 'ignore') if isinstance(value, bytes) else value
        except Exception as e:
            print(f"[EXIF Extract] {img_path} error: {e}")
        return exif_data

    def update_exif(self, img_path: str, updates: Dict[str, str]) -> None:
        """
        Update selected EXIF entries.
        """
        exif = self.extract_exif(img_path)
        exif.update(updates)
        self.inject_exif(img_path, exif)

    # ------- XMP Metadata Embed (Sidecar) --------

    def inject_xmp(self, img_path: str, xmp_data: Dict[str, str]) -> None:
        """
        Write XMP data as a sidecar (.xmp) file compatible with Google Images.
        """
        xmp_path = f"{img_path}.xmp"
        try:
            xmp_packet = create_xmp_packet(xmp_data)
            with open(xmp_path, "wb") as f:
                f.write(xmp_packet)
        except Exception as e:
            print(f"[XMP Injection] {xmp_path} error: {e}")

    def extract_xmp(self, img_path: str) -> Dict[str, str]:
        """
        Extracts sidecar XMP metadata.
        """
        xmp_path = f"{img_path}.xmp"
        if not os.path.exists(xmp_path):
            return {}
        try:
            tree = etree.parse(xmp_path)
            rdf_desc = tree.find(".//{http://www.w3.org/1999/02/22-rdf-syntax-ns#}Description")
            if rdf_desc is None:
                return {}
            result = {}
            for k, v in rdf_desc.attrib.items():
                clean = k.split('}')[-1]
                result[clean] = v
            return result
        except Exception as e:
            print(f"[XMP Extract] {xmp_path} error: {e}")
            return {}

    def update_xmp(self, img_path: str, updates: Dict[str, str]) -> None:
        """
        Update XMP sidecar file.
        """
        xmp = self.extract_xmp(img_path)
        xmp.update(updates)
        self.inject_xmp(img_path, xmp)

    # ------- File Renaming --------

    def rename_file(self, orig_path: str, new_name: str) -> str:
        """
        Rename an image file, return the new path.
        """
        dir_ = os.path.dirname(orig_path)
        ext = os.path.splitext(orig_path)[-1]
        new_path = os.path.join(dir_, new_name)
        os.rename(orig_path, new_path)
        return new_path

    # ------- Batch Processing Main --------

    def batch_process(
        self,
        context: str,
        copyright_: Optional[str] = None
    ) -> None:
        """
        Batch-process all images in image_dir:
        - SEO-rename
        - Inject EXIF/XMP with Author, Copyright, ALT
        - Alt text .json export
        """
        file_data = []
        for fname in os.listdir(self.image_dir):
            if not fname.lower().endswith(('.jpg', '.jpeg', '.webp', '.png')):
                continue

            orig_path = os.path.join(self.image_dir, fname)
            base_name = os.path.splitext(fname)[0]

            # SEO Rename
            slug = self.seo_filename(base_name)
            new_path = os.path.join(self.image_dir, slug)
            if orig_path != new_path:
                try:
                    os.rename(orig_path, new_path)
                except Exception as e:
                    print(f"[FileRename] {orig_path} → {new_path} failed: {e}")
            else:
                new_path = orig_path

            # ALT and meta
            alt = self.generate_alt(context, base_name)
            meta = {
                "Author": self.author,
                "Copyright": copyright_ or f"Copyright © 2026 {self.author}",
                "Description": alt,
            }
            # EXIF
            self.inject_exif(new_path, meta)
            # XMP (as sidecar)
            self.inject_xmp(new_path, meta)

            rec = dict(
                filename=os.path.basename(new_path),
                alt=alt,
                exif=meta,
                xmp=meta
            )
            file_data.append(rec)

        # Save all metadata as .json
        self.metadata_records = file_data
        with open(os.path.join(self.image_dir, "metadata.json"), "w", encoding="utf-8") as f:
            json.dump(file_data, f, indent=2, ensure_ascii=False)

    # ------- Extract/Update Entrypoints --------

    def extract_metadata(self, img_path: str) -> Dict:
        """
        Extract all metadata (EXIF + XMP) from a file.
        """
        info = {
            "exif": self.extract_exif(img_path),
            "xmp": self.extract_xmp(img_path),
        }
        return info

    def update_metadata(self, img_path: str, updates: Dict[str, str]) -> None:
        """
        Update EXIF and XMP metadata for an image.
        """
        self.update_exif(img_path, updates)
        self.update_xmp(img_path, updates)

# -------- Optional CLI Tool --------

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Batch meta tagger for images.")
    parser.add_argument("--dir", type=str, required=True, help="Directory of images")
    parser.add_argument("--context", type=str, required=True, help="SEO context description (e.g. article headline/topic)")
    parser.add_argument("--author", type=str, default="Nexovent AI")
    parser.add_argument("--copyright", type=str, default="")
    args = parser.parse_args()

    mgr = MetaManager(args.dir, args.author)
    mgr.batch_process(args.context, copyright_=args.copyright)
    print("Meta tagging complete. Metadata exported to metadata.json.")
